import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const meta = process.argv[2] === "metafile";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod || meta ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: true,
	metafile: true,
});

if (prod || meta) {
	const result = await context.rebuild();

	// Metafile speichern zur Analyse
	if (result.metafile) {
		await fs.writeFileSync("meta.json", JSON.stringify(result.metafile, null, 2));
		if (meta) {
			// Optional: Visualisierbare Ausgabe im Terminal (Size breakdown)
			console.log(await esbuild.analyzeMetafile(result.metafile));
		}
	}

	await context.dispose(); // Kontext sauber beenden
	process.exit(0);
} else {
	await context.watch();
}
