# https://taskfile.dev

version: "3"

vars:
    VAULT: C:\\PROJECTS\\Obsidian\\dev9\\.obsidian\\plugins\\propertyhabits

tasks:
    default:
        cmds:
            - npm run build
            - cp main.js "{{.VAULT}}\main.js"
            - cp styles.css "{{.VAULT}}\styles.css"
            - cp manifest.json "{{.VAULT}}\manifest.json"
    serena:
        cmds:
            - npm run build
            - copy main.js "{{.VAULT}}\main.js"
            - copy styles.css "{{.VAULT}}\styles.css"
            - copy manifest.json "{{.VAULT}}\manifest.json"
